version: "3.9"
services:
  database:
    container_name: database
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - fullstack
  web:
      container_name: api
      build: .
      ports:
        - "8080:8080"
      volumes:
        - .:/go/src/app
      command: bash -c "go build && ./main -b 0.0.0.0:8080 timeout 120"
      env_file:
        - .env
      environment:
        - DB_HOST=database
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
      depends_on:
        - database
      networks:
        - fullstack

volumes:
  database:

networks:
  fullstack:
    driver: bridge