version: "3.9"
services:
  api:
    container_name: api
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    command: bash -c "go build && ./main -b 0.0.0.0:8080 timeout 120"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
