version: "3.9"
services:
  api:
    container_name: api
    # env_file:
    #   - .env
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    command: bash -c "go build && ./main -b 0.0.0.0:8080 timeout 120"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
