name: CI
on:
  push:
    branches:
      - main
env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Containers 
      run: docker-compose up -d --build

    - name: Wait for DB
      uses: dadarek/wait-for-dependencies@v1
      with:
        timeout: 60
        wait-for: 'database:5432'

    - name: List Containers
      run: docker-compose ps

    - name: Run Test
      run: curl localhost:8080/tasks